export const CLI_REGEXP = /dvc\s+[a-z][a-z-.]*/
export const COMMAND_REGEXP = /^[a-z][a-z-]*$/
export const ARGS_REGEXP = new RegExp(/-{1,2}[a-zA-Z-]*/, 'ig')
export const COMMAND_ROOT = '/command-reference/'
export const CML_COMMAND_ROOT = '/doc/ref/'
export const CLI_API_REGEXP = /dvc.api([a-z-._]*\(\)$)?/
export const METHOD_REGEXP = /^[a-z-._]*\(\)$/
export const API_ROOT = '/api-reference/'
export const SIDEBAR_UPPERCASE_KEYWORDS_REGEX = /dvc|api/g
export const SIDEBAR_PATH_ROOT = ''
export const SIDEBAR_FILE_ROOT = '/docs/'
export const SIDEBAR_FILE_EXTENSION = '.md'
export const DOCS_PREFIX = ''
export const MAIN_SITE_URL = 'https://dvc.org'
export const BLOGS_URL = 'https://dvc.org/blog'
export const HOME_PAGE_LINK = '/'
