restylers:
  - name: prettier
    arguments: ['--config=./.prettierrc', '--ignore-path=./.prettierignore']
    include:
      - '**/*.json'
      - '**/*.md'
      - '**/*.mdx'
      - '**/*.yaml'
      - '**/*.yml'
