restylers:
  - name: prettier
    arguments:
      [
        '--write',
        '--arrow-parens=avoid',
        '--print-width=80',
        '--prose-wrap=always',
        '--no-semi',
        '--single-quote=true',
        '--tab-width=2',
        '--trailing-comma=none',
        '--use-tabs=false'
      ]
    include: # matching '**/*.{js,jsx,md,tsx,ts,json}'
      - '**/*.md'
      - '**/*.jsx'
      - '**/*.tsx'
      - '**/*.js'
      - '**/*.ts'
      - '**/*.json'
