name: Indexing blogs
on:
  workflow_dispatch:
    inputs:
      fullUpdate:
        default: false
        description: 'Full Index Update'
        required: false
        type: boolean
  push:
    branches: ['main']
    paths:
      - 'content/blog/**'
jobs:
  build-and-indexing-blogs:
    name: Build and indexing blogs
    runs-on: ubuntu-latest
    env:
      GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
      ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
      GATSBY_ALGOLIA_INDEX_NAME: ${{ secrets.GATSBY_ALGOLIA_INDEX_NAME }}
      ALGOLIA_FULL_UPDATE: ${{ github.event.inputs.fullUpdate }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js and use yarn
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'yarn'
      - name: Gatsby Cache and Public Folder
        uses: actions/cache@v2
        with:
          key: gatsby-cache-and-public-folder
          path: |
            .cache
            public
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Build and index blogs on postBuild
        run: yarn run build
