name: Indexing blogs
on:
  push:
    branches: ['search-blogs-ci-indexing']
    paths:
      - 'content/blog/**'
jobs:
  build-and-indexing-blogs:
    name: Build and indexing blogs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js and use yarn
        uses: actions/setup-node@v2
        env:
          GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          GATSBY_ALGOLIA_INDEX_NAME: ${{ secrets.GATSBY_ALGOLIA_INDEX_NAME }}
        with:
          node-version: '14.x'
          cache: 'yarn'
      - name: Gatsby Cache Folder
        uses: actions/cache@v2
        with:
          key: gatsby-cache-folder
          path: .cache
      - name: Gatsby Public Folder
        uses: actions/cache@v2
        with:
          key: gatsby-public-folder
          path: public
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Build and index blogs on postBuild
        run: yarn run build
