name: Download Link Check

on:
  pull_request: # here for testing
  deployment_status:
  schedule:
    - cron: '0 1-23 * * *'

jobs:
  run:
    name: Initialize
    runs-on: ubuntu-latest
    # if:
    # github.event.deployment.ref != 'master' &&
    # github.event.deployment_status.state == 'success'
    steps:
      - uses: actions/checkout@v2
      - name: Download Link Checker
        uses: lycheeverse/lychee-action@v1.0.8
        with:
          args:
            -v --include https:\/\/s3-us-east-2\.amazonaws\.com\/dvc
            https://dvc.org/
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      # - name: Create Issue From File
      #   uses: peter-evans/create-issue-from-file@v3
      #   with:
      #     title: Link Checker Report
      #     content-filepath: ./lychee/out.md
      #     labels: website, automated issue
      - name: Create Report for Broken Links
        run: echo "create issue here"
      - name: Create SUCCESSFUL_LINK_AMOUNT env
        run: |
          text=$(grep Successful ./lychee/out.md)
          amount="${text//[^0-9]/}"
          echo SUCCESSFUL_LINK_AMOUNT=$amount >> $GITHUB_ENV
      - if: ${{ env.SUCCESSFUL_LINK_AMOUNT != '4' }}
        # name: Create Issue From File
        # uses: peter-evans/create-issue-from-file@v3
        # with:
        #   title: Link Checker Report
        #   content-filepath: ./lychee/out.md
        #   labels: website, automated issue
        name: Create Report for Missing Links
        run: echo "create issue here"
